### ISSUE TITLE
Add gradle caching

### ISSUE THREAD

**Issue by moifort** [moifort/jhipster-gitlab-ci-image#1]
@atomfrede I did not forget you :)
- Create a new branche with new tag type `XX.X.X-cache-maven` and `XX.X.X-cache-gradle`
- update README.md

**Comment by pascalgrimaud** [comment]
Be careful about the size of repository in Github

**Comment by moifort** [comment]
There is a limitation? it's around 1.3 Go.

**Comment by pascalgrimaud** [comment]
Around 1go if I remember well. And m2+node_modules+gradle can grow quickly, so for a long support, I think better to separate gradle and maven

**Comment by moifort** [comment]
Thanks you for the tip!

**Comment by atomfrede** [comment]
@moifort I would like to update your image with new dependencies. Should we create another image for gradle cache right now?

**Comment by moifort** [comment]
I think the best is I share my github project with you (tell me if you have access at this repo). When your image works you create a new tag (for instance: JHIPSTER_VERSION-GRADLE). And when you push your commit it will trigger the build on docker hub.

Or if you prefer to create a new repo directly in JHipster group, maybe it will be better?

What do you think?

**Comment by atomfrede** [comment]
I have access now thanks! What about the seperation of gradle and maven into two repositories? I have no idea how fast we might hit the size restriction. 

Creating a repository and image directly in jhipster might be better as images under some "organization" are often more trusted, but for the moment we can keep it under personal namespace I guess.

**Comment by pascalgrimaud** [comment]
Or under the jhipster Labs? I was thinking to migrate all my modules to it

**Comment by pascalgrimaud** [comment]
About jhipster Labs, I have to look if we can link to travis and Docker hub too

**Comment by atomfrede** [comment]
Sounds good. I'll do some testing and post my results here.

**Comment by moifort** [comment]
For me, there is no problem to put it in JHipster lab (I think it's better), I am not good enough in docker to say if it's better to split or to make in the same project, take what is the easier for you 😄. 

By the way, sorry because I am not very active at the moment, but I will work again soon!

**Comment by pascalgrimaud** [comment]
Dont be sorry, @moifort !!
We are in an open source project, nothing mandatory. You contribute when you want and when you have time. No pressure :beer:
That's why I love JHipster

**Comment by atomfrede** [comment]
Exactly! Don't be sorry!

**Comment by moifort** [comment]
Thanks guys!

**Comment by atomfrede** [comment]
My current idea:

* Plain image that only contains required frontend dependencies ``hipster-labs/gitlab-ci`` (extending java image)
* Images with cache extending the base image: ``hipster-labs/gitlab-ci-gradle``, ``hipster-labs/gitlab-ci-maven``

The caches should contain all dependencies (for monolithic apps and microservices) and all node_modules (which didn't worked for me now, I guess somehow the executable for phantom was broken during checkin)

**Comment by pascalgrimaud** [comment]
cache is very hard to maintain because it can change all the time when we upgrade lib.
But if you update your docker image, people who uses old version of JHipster won't use the same cache

**Comment by atomfrede** [comment]
Yes its not easy to maintain, but I think we must provide an image with "pre cached" libraries. Otherwise shared runners will be somehow not useable (e.g. it will download mvn/gradle wrapper for each build). I liked @moifort idea to tag the docker images with the corresponding jhipster version, such that a ci image vor 3.0.0 has cached the default dependencies for 3.0.0. In case you have an own specific runner (no autoscaling) you can just use [the approach I had in mind before](https://atomfrede.github.io/shiny-adventure/2016/04/03/Cache-in-Gitlab-C-I.html).

mvn without cache: ~ 8 Minutes (~3 minutes with cache)
gradle without cache: ~ 12 minutes (~3 minutes with cache)

**Comment by pascalgrimaud** [comment]
Yes agree to try to use cache! Not easy but not impossible. And the tag at docker hub will help a lot

**Comment by moifort** [comment]
@atomfrede  do you want the access to my docker hub for testing?

**Comment by atomfrede** [comment]
I can use mine for the moment. I have setup two sample projects.
